### ISSUE TITLE
Error hostile portal

### ISSUE THREAD

**Issue by electron64** [s0lst1c3/eaphammer#13]
Hello, i get an error when i launch --hostile portal option.
Do you have an idea  where it comes from?

[*] Starting process: dnsspoof

100%|█████████████████████████████████████████████| 2/2 [00:02<00:00,  1.00s/it]

Traceback (most recent call last):
  File "eaphammer.py", line 325, in <module>
    hostile_portal()
  File "eaphammer.py", line 79, in hostile_portal
    responder.configure()
  File "/root/eaphammer/core/responder/responder.py", line 267, in configure
    settings.Config.populate(options)
  File "/root/eaphammer/core/responder/settings.py", line 77, in populate
    self.HTTP_On_Off     = self.toBool(config.get('Responder Core', 'HTTP'))
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Responder Core'

**Comment by s0lst1c3** [comment]
Hey @electron64, try pulling the latest update and giving it another shot. If that doesn't work, we'll go from there. Thanks.

**Comment by electron64** [comment]
Hi ,s0lst1c3 
i'll try with the last update.
Thank's.

**Comment by s0lst1c3** [comment]
Closing due to inactivity. Let me know if you're still running into problems. Thanks.
