### ISSUE TITLE
No module named '_cffi_backend'

### ISSUE THREAD

**Issue by DroidKali** [s0lst1c3/eaphammer#162]
```
./eaphammer                
Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/root/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/root/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/root/eaphammer/cert_wizard/cert_utils.py", line 7, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```
```
pip3 install cffi
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Requirement already satisfied: cffi in /usr/local/lib/python3.9/dist-packages (1.14.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi) (2.20)
```
Is there anyone can help me？

**Comment by DroidKali** [comment]
Is this repo died？

**Comment by s0lst1c3** [comment]
Nah homie I just have a day job. You're welcome to submit a pull request in the meantime.

**Comment by s0lst1c3** [comment]
Can you do me a huge favor? Resubmit this issue using the "Bug report" template found here:

https://github.com/s0lst1c3/eaphammer/issues/new/choose

Please make sure to fill out all the required fields. Thanks.

**Comment by DroidKali** [comment]
Have submited！
https://github.com/s0lst1c3/eaphammer/issues/163

**Comment by DroidKali** [comment]
@s0lst1c3 https://github.com/s0lst1c3/eaphammer/pull/165
