### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by DroidKali** [s0lst1c3/eaphammer#163]
**Describe the bug**
```
🚀 ~/eaphammer/ [master*] ./eaphammer 
Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/root/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/root/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/root/eaphammer/cert_wizard/cert_utils.py", line 7, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
🚀 ~/eaphammer/ [master*] 
```
```
🚀 ~/eaphammer/ [master*] pip3 install cffi
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Requirement already satisfied: cffi in /usr/lib/python3/dist-packages (1.14.4)
🚀 ~/eaphammer/ [master*] 
```

**To Reproduce**

1. git clone https://github.com/s0lst1c3/eaphammer.git --depth=1
2. cd eaphammer
3. ./kali-setup
4. ./eaphammer

**Expected behavior**

**Screenshots**

https://imgchr.com/i/rU0aAP

**Command string(s) used**

The exact command(s) you used to trigger the bug.

**EAPHammer verbose output (using the --debug flag)**

Paste _redacted_ output here.

**EAPHammer Version (./eaphammer --version)**

```
🚀 ~/eaphammer/ [master*] ./eaphammer --version
Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/root/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/root/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/root/eaphammer/cert_wizard/cert_utils.py", line 7, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
🚀 ~/eaphammer/ [master*] 
```

**OS (the OS from which you are running EAPHammer)**

Linux kali 5.9.0-kali4-amd64 #1 SMP Debian 5.9.11-1kali1 (2020-12-01) x86_64 GNU/Linux

**Configuration of Target Access Point (if known / applicable)**

Fill this in if possible.

**Configuration of Target Client Device (if known / applicable)**

Fill this in if possible.

**Additional context**

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
