### ISSUE TITLE
PMKID attack with essid option - invalid literal for int() with base 10

### ISSUE THREAD

**Issue by rouxn-bsi** [s0lst1c3/eaphammer#211]
**Description**

eaphammer is crashing using the --pmkid and --essid parameters.
I understand the tool is searching the channel but it seem to expect an get an "int" when a string is returned (or the string is incorrectly parsed).

**Steps to reproduce the behavior:**

1. Latest Kali
2. Alfa AC1900
3. sudo eaphammer --pmkid --interface wlan0 --essid "FIXME"

**Expected behavior**

Not crashing ;-)

**Screenshots**

![image](https://github.com/s0lst1c3/eaphammer/assets/69321109/fd80b1e6-107c-4ae2-b0d6-469b4f576730)

**Command string(s) used**

sudo eaphammer --pmkid --interface wlan0 --essid "FIXME"

Traceback (most recent call last):
  File "/usr/share/eaphammer/./eaphammer", line 1209, in <module>
    pmkid_attack()
  File "/usr/share/eaphammer/./eaphammer", line 922, in pmkid_attack
    channel = iw_parse.helper_functions.find_channel_from_bssid(bssid, networks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/eaphammer/core/iw_parse/helper_functions.py", line 4, in find_channel_from_bssid
    return int(n['Channel'])
           ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '5.66 GHz (Channel 132)'

**OS (the OS from which you are running EAPHammer)**

Kali OS

**Configuration of Target Client Device (if known / applicable)**

Alfa AC1900

**Comment by rouxn-bsi** [comment]
I tried to set the channel but it crashed the same.
