### ISSUE TITLE
Error kali linux distro 

### ISSUE THREAD

**Issue by anideb1975** [s0lst1c3/eaphammer#217]
Hi
kali linux run 
#eaphammer -h
this is my output

Traceback (most recent call last):
  File "/usr/share/eaphammer/./eaphammer", line 5, in <module>
    import core.cli
  File "/usr/share/eaphammer/core/__init__.py", line 10, in <module>
    from . import wskeyloggerd
  File "/usr/share/eaphammer/core/wskeyloggerd/__init__.py", line 1, in <module>
    from core.wskeyloggerd.app import run
  File "/usr/share/eaphammer/core/wskeyloggerd/app.py", line 79, in <module>
    socketio                    = SocketIO(app, cors_allowed_origins="*")
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/flask_socketio/__init__.py", line 187, in __init__
    self.init_app(app, **kwargs)
  File "/usr/lib/python3/dist-packages/flask_socketio/__init__.py", line 243, in init_app
    self.server = socketio.Server(**self.server_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/socketio/base_server.py", line 31, in __init__
    self.eio = self._engineio_server_class()(**engineio_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/engineio/base_server.py", line 81, in __init__
    raise ValueError('Invalid async_mode specified')
ValueError: Invalid async_mode specified

**Expected behavior**

**Screenshots**

**Command string(s) used**

The exact command(s) you used to trigger the bug.

**EAPHammer verbose output (using the --debug flag)**

Paste _redacted_ output here.

**EAPHammer Version (./eaphammer --version)**

Paste output here.

**OS (the OS from which you are running EAPHammer)**

Fill this in.

**Configuration of Target Access Point (if known / applicable)**

Fill this in if possible.

**Configuration of Target Client Device (if known / applicable)**

Fill this in if possible.

**Additional context**

**Comment by anideb1975** [comment]
I'm starting to believe it's the python version, try version 3.8

**Comment by anideb1975** [comment]
currently the version of python on kali linux is 3.11
