### ISSUE TITLE
not defined config option llmnr

### ISSUE THREAD

**Issue by Commander99** [s0lst1c3/eaphammer#225]
Hey, as soon as i try to create a hostile portal ap i get this traceback error: 

Traceback (most recent call last):
  File "/usr/lib/python3.12/configparser.py", line 767, in get
    value = d[option]
            ~^^^^^^^^
  File "/usr/lib/python3.12/collections/__init__.py", line 1015, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/collections/__init__.py", line 1007, in __missing__
    raise KeyError(key)
KeyError: 'llmnr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/eaphammer/local/Responder/Responder.py", line 64, in <module>
    settings.Config.populate(options)
  File "/usr/share/responder/settings.py", line 119, in populate
    self.LLMNR_On_Off    = self.toBool(config.get('Responder Core', 'LLMNR'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 770, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'llmnr' in section: 'Responder Core'

I already located the config file under /usr/share/Responder/Responder.conf. The head of the file looks like this: [Responder Core]

; Poisoners to start
MDNS  = On
LLMNR = On
NBTNS = On

; Servers to start
SQL      = On
SMB      = On
RDP      = On
Kerberos = On
FTP      = On
POP      = On
SMTP     = On
IMAP     = On
HTTP     = On
HTTPS    = On
DNS      = On
LDAP     = On
DCERPC   = On
WINRM    = On
SNMP     = Off
MQTT     = On
Then i found another config file /etc/responder/Responder.conf. This time the file doesn't contain llmnr at all. I added llmnr = On to the second file aswell but it got overwritten and deleted as soon as i started eaphammer. Im not sure if thats an issue on my side or how to resolve it.

**Comment by unsinc** [comment]
same here.

**Comment by testsinx74** [comment]
I solved this.

If you are using eaphammer from https://github.com/s0lst1c3/eaphammer

Add the following right below [Responder Core] in this file: eaphammer/settings/core/Responder.ini

llmnr = On
nbtns = On
mdns = On
dontrespondtotld = On

If you installed eaphammer via apt, add the same lines, but to /usr/share/eaphammer/settings/core/Responder.ini instead

Hope that helps

**Comment by ericescobar** [comment]
Also add:

quic = Off
