### ISSUE TITLE
Error when runing cert gen script

### ISSUE THREAD

**Issue by wice222** [s0lst1c3/eaphammer#4]
HI , I'm getting IOerror when generating SSL:

```
[*] Please enter two letter country code for certs (i.e. US, FR)
: ie
[*] Please enter state or province for certs (i.e. Ontario, New Jersey)
: dub
[*] Please enter locale for certs (i.e. London, Hong Kong)
: dub
[*] Please enter organization for certs (i.e. Evil Corp)
: werldlander
[*] Please enter email for certs (i.e. cyberz@h4x0r.lulz)
: ucd@worldlander.lulz
[*] Please enter common name (CN) for certs.
: worldlander.lulz
Traceback (most recent call last):
  File "./eaphammer", line 319, in <module>
    cert_wizard()
  File "./eaphammer", line 38, in cert_wizard
    cert_manager.ca_cnf.configure(country, state, locale, org, email, cn)
  File "/root/Desktop/eaphammer-fixingDepIssues/core/cert_manager.py", line 16, in configure
    with open(cls.path, 'w') as fd:
IOError: [Errno 2] No such file or directory: './certs/ca.cnf'
```
I'm doing something wrong ?

**Comment by s0lst1c3** [comment]
Hey @wice222, it looks like the cert directory didn't get uploaded in the latest commit. I've corrected the issue and will commit changes shortly. Let me know if they addres your issue.

**Comment by s0lst1c3** [comment]
Fixed in https://github.com/s0lst1c3/eaphammer/commit/fe9e7459ee2a1fdf93bfd5529131b7d401225027.

**Comment by wice222** [comment]
Hi, Thanks for your answer, 
I see the files were refreshed , and I cloned them again on fresh Kali2
But this time script dont even starts:

```
root@kali:~/Desktop/eaphammer-master# ./eaphammer --cert-wizard
Traceback (most recent call last):
  File "./eaphammer", line 9, in <module>
    from core import cert_manager, conf_manager, utils, responder
  File "/root/Desktop/eaphammer-master/core/__init__.py", line 3, in <module>
    import utils
  File "/root/Desktop/eaphammer-master/core/utils.py", line 4, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm
```
